### PR TITLE
fix: SecretStoreExclusive must have an initial sub-path in `Path` specified.

### PR DESCRIPTION
**Pull request by lenny-intel**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

User must specify `Path` when Storing Secrets, which is a bug. Should be able to leave `Path` empty

Issue Number: #119  

## What is the new behavior?

Storing Secrets empty `Path`  works

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
no

## Other information

### CODE REVIEW

**Comment by bnevis-i** [comment]
> User must specify Path when Storing Secrets, which is a bug. Should be able to leave Path empty

I disagree with this assessment.  The "path" is actually the name of the secret, and the secret is a collection of key-value pairs.  The unity of granularity is the key-value pair object.

**Comment by bnevis-i** [comment]
Some of the paths in the configuration files have trailing slashes (/app/) while some do not (/app)

**Comment by lenny-intel** [comment]
@bnevis-i , The more I thought about this I came to realize that this is a breaking change. If I stored secrets with previous release ASC using `Path=mqtt` which uses sub-path of `/mqtt` and then switch to this version of ASC, I would not find my secrets due to the sub path now becomes /app/mqtt. The correct `fix` is to make `Path` required for Secrets API (aka Store Secrets), then all this goes away... ;-) And it doesn't break anything since storing w/o path doesn't work...

**Comment by bnevis-i** [comment]
@lenny-intel How change the app sdk such that if path is empty, just plug in "default"

**Comment by bnevis-i** [comment]
@lenny-intel And may be rename the "path" argument to "secretname"

**Comment by lenny-intel** [comment]
> rename the "path" argument to "secretname"

@bnevis-i Maybe for V2, but this would be breaking change for V1. Come to today's App Service WG at 4:30pm PDT. This will be on the agenda.

**Comment by lenny-intel** [comment]
This is a breaking  change. Closing

**Pull request closed without merging**
