### PR TITLE
fix(snap): fix README's security-secret-store doc

### PR DESCRIPTION
**Pull request by tonyespy**
The snap's `README` incorrectly stated that security-secret-store could be set to `false` to disable secret store usage. The correct value is `off`.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
NA

Issue Number: NA

## What is the new behavior?
NA

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
No

## Are there any specific instructions or things that should be known prior to reviewing?
No

## Other information

### CODE REVIEW

**Review by lenny-intel — DISMISSED** [review]

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by tonyespy** [comment]
Just re-based and force pushed...

**Review by lenny-intel — APPROVED** [review]

**Pull request merged**
