### PR TITLE
refactor!: Renamed SecretName to SecretValueKey and SecretnPath to SecretName

### PR DESCRIPTION
**Pull request by marcpfuller**
BREAKING CHANGE: Renamed SecretName to SecretValueKey and SecretPath to SecretName

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-service-configurable/blob/main/.github/CONTRIBUTING.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) N/A
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?) 
- [ ] I have opened a PR for the related docs change (if not, why?) N/A
  <link to docs PR>

## Testing Instructions
`make test`
startup edgex
run each profile individually to verify each started up successfully and are functioning correctly
run `./app-service-configurable -p sample -cp`
run `./app-service-configurable -p mqtt-export -cp`
run `./app-service-configurable -p http-export -cp`
run `./app-service-configurable -p functional-tests -cp`
run `./app-service-configurable -p metrics-influxdb -cp`
run `./app-service-configurable -p rules-engine -cp`

### CODE REVIEW

**Review by jim-wang-intel — DISMISSED** [review]
LGTM

**Review by lenny-intel — CHANGES_REQUESTED** [review]
Missing changes to all the InsecureSecrets

**Review by lenny-intel — APPROVED** [review]
LGTM

**Comment by lenny-intel** [comment]
@marcpfuller , for testing, `make test` doesn't do much as there are not any unit tests. You need to run ASC with each profile and a at minimum verify they each start-up.

**Comment by marcpfuller** [comment]
> @marcpfuller , for testing, `make test` doesn't do much as there are not any unit tests. You need to run ASC with each profile and a at minimum verify they each start-up.

I just ran through each profile and all ran without issue

**Review by lenny-intel — APPROVED** [review]
LGTM

**Pull request merged**
