### PR TITLE
Corrected the mqtt-export related environment variable overrides in README.

### PR DESCRIPTION
**Pull request by drensber**
Issue https://github.com/edgexfoundry/app-service-configurable/issues/43

### CODE REVIEW

**Comment by lenny-intel** [comment]
@drensber , you need to `sign-off` your commit. Se the details next to the failed DCO

**Comment by drensber** [comment]
I think it should be good now. Sorry, I tried to do the whole thing through the GitHub GUI. Evidently you can't do that because of the sign off requirement.

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
recheck

**Comment by lenny-intel** [comment]
@drensber , can you please do a rebase and force push or another commit to redo the verify jobs? recheck comment no longer works.

**Comment by drensber** [comment]
Just did a rebase and another commit/signoff and push.  Hopefully it did
what it needs to do this time?

--Dave

**Comment by lenny-intel** [comment]
@drensber , nope. I should be ignoring the old verify job, but it isn't. Please close this PR and create a new one and see if that works.

**Comment by drensber** [comment]
Closing and trying again with PR #45.

**Comment by lenny-intel** [comment]
@drensber , no worries. It was bad timing with the CI changes DevOps made to switch to the new Jenkins pipeline. Looks like to old job is now gone, so we should be good.

**Pull request closed without merging**
